### ISSUE TITLE
Your code is bad and you should feel bad lmaoooooo

### ISSUE THREAD

**Issue by Jussinevavuori** [jusvait/HelplyBackend#1]
```
fn get_severity(text: &str, estimate: &i32 ) -> String {
    let mut weight = 0;
    weight += estimate + 1;
    ...
```

This is bad practice. Please write `let mut weight = estimate + 1` instead. Also consider renaming `weight`to `sis`.

**Comment by Jussinevavuori** [comment]
wait no

**Comment by HansenFeng** [comment]
Please feel free to open a PR if you want this fixed, strict no refund policy here

**Comment by IvarK** [comment]
no u
